#define LUA_OPADD   0
#define LUA_OPSUB   1
#define LUA_OPMUL   2
#define LUA_OPMOD   3
#define LUA_OPPOW   4
#define LUA_OPDIV   5
#define LUA_OPIDIV  6
#define LUA_OPBAND  7
#define LUA_OPBOR   8
#define LUA_OPBXOR  9
#define LUA_OPSHL   10
#define LUA_OPSHR   11
#define LUA_OPUNM   12
#define LUA_OPBNOT  13
